class ScrollyNavigation {
  constructor(containerId, presentationId) {
    this.containerId = containerId;
    this.presentationId = presentationId; // Identificador único (ex: 'aula-01')
    this.container = document.getElementById(containerId);
    this.slides = [];
    this.navContainer = null;
    
    this.storageKey = `scrolly_idx_${this.presentationId || 'default'}`;
  }

  init() {
    if (!this.container) {
      console.error(`ScrollyNavigation: Elemento "${this.containerId}" não encontrado.`);
      return;
    }

    this.slides = Array.from(this.container.querySelectorAll('.slide'));
    
    if (this.slides.length === 0) return;

    this._setupReveals();
    this._createNavDots();
    this._initObserver();
    this._initWheel();
    this._initKeyboard();
    
    // Handler de scroll para controlar reveals
    // MUDANÇA: Ouvimos o container de scroll, não a janela
    this.container.addEventListener('scroll', () => this._onScroll());

    // MUDANÇA 2: Restaurar posição ao iniciar
    this._restorePosition();
  }

  // --- CONFIGURAÇÃO DE REVEALS ---
  _setupReveals() {
    this.slides.forEach(slide => {
      // FIX: Select correct classes generated by renderer
      const revealItems = slide.querySelectorAll('.reveal-block, .reveal-item');
      if (revealItems.length > 0) {
        // Altura extra baseada no número de itens para revelar
        // Cada item adiciona 50vh de scroll
        const scrollHeight = 100 + (revealItems.length * 50);
        slide.style.height = `${scrollHeight}vh`;
        slide.classList.add('has-reveal'); // Enable CSS structural changes
        
        // Separa conteúdo existente em um wrapper sticky
        const content = document.createElement('div');
        content.className = 'slide-content';
        while (slide.firstChild) {
            content.appendChild(slide.firstChild);
        }
        slide.appendChild(content);

        // Inicializa itens como hidden (renderer já faz, mas garante estado)
        revealItems.forEach(item => {
            item.classList.add('reveal-hidden');
            item.classList.remove('reveal-visible');
        });
      }
    });
  }

  // --- SCROLL HANDLER (Visual Only) ---
  _onScroll() {
    this.slides.forEach((slide, index) => {
      const rect = slide.getBoundingClientRect();
      const revealItems = slide.querySelectorAll('.reveal-block, .reveal-item');
      
      if (revealItems.length === 0) return;

      // Check if slide is active (top <= 0)
      // Relaxed condition: as soon as it starts scrolling off screen
      if (rect.top <= 1 && rect.bottom >= 0) {
        
        const scrollDistance = Math.abs(rect.top);
        const stepSize = window.innerHeight * 0.5;

        // Direct mapping: 1 step = 1 item
        // At 0px: index -1 (all hidden)
        // At 50vh: index 0 (1st item)
        let activeIndex = Math.floor(scrollDistance / stepSize) - 1;

        // Clamp index
        if (activeIndex >= revealItems.length) activeIndex = revealItems.length - 1;
        
        revealItems.forEach((item, i) => {
          if (i <= activeIndex) {
            item.classList.remove('reveal-hidden');
            item.classList.add('reveal-visible');
          } else {
            item.classList.add('reveal-hidden');
            item.classList.remove('reveal-visible');
          }
        });
      }
    });
  }

  // --- NOVO MÉTODO: Restaurar Posição ---
  _restorePosition() {
    const savedIndex = localStorage.getItem(this.storageKey);
    
    if (savedIndex !== null) {
      const index = parseInt(savedIndex, 10);
      const targetSlide = this.slides[index];

      if (targetSlide) {
        console.log(`Restaurando para o slide ${index + 1}`);
        // Usa behavior: 'auto' para pular instantaneamente (sem animação suave)
        // Isso evita que o usuário veja a rolagem acontecendo ao dar F5
        targetSlide.scrollIntoView({ behavior: 'instant', block: 'start' });
        
        // Atualiza a bolinha ativa visualmente
        this._updateDotsUI(index);
      }
    }
  }

  _createNavDots() {
    let nav = document.getElementById('slide-nav');
    if (!nav) {
      nav = document.createElement('div');
      nav.id = 'slide-nav';
      document.body.appendChild(nav);
    }
    nav.innerHTML = '';
    this.navContainer = nav;

    this.slides.forEach((slide, index) => {
      const dot = document.createElement('div');
      dot.className = 'nav-dot';
      dot.dataset.index = index;
      dot.title = `Slide ${index + 1}`;
      
      dot.addEventListener('click', () => {
        // Ao clicar, salvamos manualmente também
        this._savePosition(index);
        slide.scrollIntoView({ behavior: 'smooth', block: 'start' });
      });

      nav.appendChild(dot);
    });
  }

  _initObserver() {
    const observerOptions = {
      root: null, // viewport
      threshold: 0.1 // Detecta quando 10% do slide está visível
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          // Encontra qual slide está ocupando a maior parte da tela?
          // Simplificação: se intersectar, consideramos candidato.
          // Melhor: verificar qual está mais próximo do centro.
          const index = this.slides.indexOf(entry.target);
          if (index !== -1) {
             // Só atualiza UI se estiver realmente "focado".
             // Aqui, vamos confiar que o scroll snap ou o usuário parou nele.
             // Para garantir, podemos checar se o top está proximo de 0?
             // Deixa simples por enquanto.
            this._updateDotsUI(index);
            this._savePosition(index);
          }
        }
      });
    }, observerOptions);

    this.slides.forEach(slide => observer.observe(slide));
  }

  // Separei a lógica visual para reutilizar no restorePosition
  _updateDotsUI(activeIndex) {
    if (!this.navContainer) return;
    const dots = this.navContainer.querySelectorAll('.nav-dot');
    dots.forEach(dot => dot.classList.remove('active'));
    
    if (dots[activeIndex]) {
      dots[activeIndex].classList.add('active');
    }
  }

  // --- NOVO MÉTODO: Salvar Posição ---
  _savePosition(index) {
    localStorage.setItem(this.storageKey, index);
  }

  // --- NAVEGAÇÃO CENTRALIZADA (Helpers) ---

  _getCurrentSlideInfo() {
      // Robust detection: Find the slide that contains the vertical center of the screen
      const middleY = window.innerHeight / 2;
      
      let currentIndex = this.slides.findIndex(slide => {
          const rect = slide.getBoundingClientRect();
          // Slide covers the middle line?
          return rect.top <= middleY && rect.bottom >= middleY;
      });

      // Fallback strategies if logic above fails (unlikely but possible during fast scrolls)
      if (currentIndex === -1) {
          // Try finding closest to top 0
          currentIndex = this.slides.findIndex(slide => {
              const rect = slide.getBoundingClientRect();
              return Math.abs(rect.top) < window.innerHeight; 
          });
      }

      if (currentIndex === -1) currentIndex = 0;
      
      // Update UI if needed (just in case observer missed it)
      this._updateDotsUI(currentIndex);

      return { 
          index: currentIndex, 
          slide: this.slides[currentIndex] 
      };
  }

  _navigateNext() {
      const { index, slide } = this._getCurrentSlideInfo();
      const scrollStep = window.innerHeight * 0.5;

      // 1. Tenta scrollar reveals internos
      const revealItems = slide.querySelectorAll('.reveal-block, .reveal-item');
      if (revealItems.length > 0) {
          const rect = slide.getBoundingClientRect();
          // Se ainda tem espaço > (altura da janela + tolerância)
          if (rect.bottom > window.innerHeight + 10) {
              this.container.scrollBy({ top: scrollStep, behavior: 'smooth' });
              return;
          }
      }

      // 2. Vai para o próximo slide
      this._scrollToNextSlide(index);
  }

  _navigatePrev() {
      const { index, slide } = this._getCurrentSlideInfo();
      const scrollStep = window.innerHeight * 0.5;

      // 1. Tenta scrollar para cima em reveals internos
      const revealItems = slide.querySelectorAll('.reveal-block, .reveal-item');
      if (revealItems.length > 0) {
           const rect = slide.getBoundingClientRect();
           // Se o topo está acima de 0 (ou seja, já rolamos para baixo), voltamos
           if (rect.top < -10) {
               this.container.scrollBy({ top: -scrollStep, behavior: 'smooth' });
               return;
           }
      }

      // 2. Vai para o slide anterior
      const prevIndex = index - 1;
      if (prevIndex >= 0) {
        this.slides[prevIndex].scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
  }

  _scrollToNextSlide(currentIndex) {
      const nextIndex = currentIndex + 1;
      if (nextIndex < this.slides.length) {
          this.slides[nextIndex].scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
  }

  _initKeyboard() {
    document.addEventListener('keydown', (e) => {
      // Ignora se estiver focado em iframe
      if (document.activeElement.tagName === 'IFRAME') return;

      if (e.key === 'ArrowDown' || e.key === ' ' || e.key === 'Enter') {
        e.preventDefault();
        this._navigateNext();
      } 
      else if (e.key === 'PageDown') {
        e.preventDefault();
        // PageDown agora força ir para o próximo slide
        const { index } = this._getCurrentSlideInfo();
        this._scrollToNextSlide(index);
      }
      else if (e.key === 'ArrowUp' || e.key === 'PageUp') {
        e.preventDefault();
        this._navigatePrev();
      }
    });

    // Ajuste no click para usar a mesma lógica
    this.slides.forEach(slide => {
        slide.addEventListener('click', (e) => {
            if (e.target.tagName === 'A' || e.target.tagName === 'BUTTON') return;
            this._navigateNext();
        });
    });
  }

  _initWheel() {
      // Debounce simples
      let isProcessing = false;
      
      this.container.addEventListener('wheel', (e) => {
          e.preventDefault(); // Impede scroll nativo para ter controle total

          if (isProcessing) return;

          // Limiar para considerar um "tick" de roda
          if (Math.abs(e.deltaY) > 10) {
              isProcessing = true;
              
              if (e.deltaY > 0) {
                  this._navigateNext();
              } else {
                  this._navigatePrev();
              }

              // Cooldown de 100ms
              setTimeout(() => {
                  isProcessing = false;
              }, 100);
          }
      }, { passive: false }); // passive: false é necessário para preventDefault funcionar
  }
}