class ScrollyNavigation {
  constructor(containerId, presentationId) {
    this.containerId = containerId;
    this.presentationId = presentationId; // Identificador único (ex: 'aula-01')
    this.container = document.getElementById(containerId);
    this.slides = [];
    this.navContainer = null;
    
    this.storageKey = `scrolly_idx_${this.presentationId || 'default'}`;
  }

  init() {
    if (!this.container) {
      console.error(`ScrollyNavigation: Elemento "${this.containerId}" não encontrado.`);
      return;
    }

    this.slides = Array.from(this.container.querySelectorAll('.slide'));
    
    if (this.slides.length === 0) return;

    this._setupReveals();
    this._createNavDots();
    this._initObserver();
    this._initKeyboard();
    
    // Handler de scroll para controlar reveals
    // MUDANÇA: Ouvimos o container de scroll, não a janela
    this.container.addEventListener('scroll', () => this._onScroll());

    // MUDANÇA 2: Restaurar posição ao iniciar
    this._restorePosition();
  }

  // --- CONFIGURAÇÃO DE REVEALS ---
  _setupReveals() {
    this.slides.forEach(slide => {
      // FIX: Select correct classes generated by renderer
      const revealItems = slide.querySelectorAll('.reveal-block, .reveal-item');
      if (revealItems.length > 0) {
        // Altura extra baseada no número de itens para revelar
        // Cada item adiciona 50vh de scroll
        const scrollHeight = 100 + (revealItems.length * 50);
        slide.style.height = `${scrollHeight}vh`;
        slide.classList.add('has-reveal'); // Enable CSS structural changes
        
        // Separa conteúdo existente em um wrapper sticky
        const content = document.createElement('div');
        content.className = 'slide-content';
        while (slide.firstChild) {
            content.appendChild(slide.firstChild);
        }
        slide.appendChild(content);

        // Inicializa itens como hidden (renderer já faz, mas garante estado)
        revealItems.forEach(item => {
            item.classList.add('reveal-hidden');
            item.classList.remove('reveal-visible');
        });
      }
    });
  }

  // --- SCROLL HANDLER ---
  _onScroll() {
    this.slides.forEach((slide, index) => {
      const rect = slide.getBoundingClientRect();
      const revealItems = slide.querySelectorAll('.reveal-block, .reveal-item');
      
      if (revealItems.length === 0) return;

      // Se o slide está visível na tela (o topo passou do 0 mas o fundo ainda não passou tudo)
      if (rect.top <= 0 && rect.bottom >= window.innerHeight) {
        // Calcula quanto "andamos" dentro do slide
        // O slide começa em rect.top = 0. Conforme subimos, rect.top fica negativo.
        const scrollDistance = Math.abs(rect.top);
        const totalScrollableHeight = rect.height - window.innerHeight;
        
        // Progresso de 0 a 1
        let progress = 0;
        if (totalScrollableHeight > 0) {
            progress = scrollDistance / totalScrollableHeight;
        }

        // Mapeia progresso para índice de itens
        const totalItems = revealItems.length;
        // Queremos revelar o item 1 em X%, item 2 em Y%...
        // Vamos simplificar: cada item tem um "slot" de scroll.
        
        // Ajuste no cálculo para ficar mais responsivo
        // (progress * totalItems) dá o índice float.
        const activeIndex = Math.floor(progress * (totalItems + 1)) - 1;

        revealItems.forEach((item, i) => {
          if (i <= activeIndex) {
            item.classList.remove('reveal-hidden');
            item.classList.add('reveal-visible');
          } else {
            item.classList.add('reveal-hidden');
            item.classList.remove('reveal-visible');
          }
        });
      }
    });
  }

  // --- NOVO MÉTODO: Restaurar Posição ---
  _restorePosition() {
    const savedIndex = localStorage.getItem(this.storageKey);
    
    if (savedIndex !== null) {
      const index = parseInt(savedIndex, 10);
      const targetSlide = this.slides[index];

      if (targetSlide) {
        console.log(`Restaurando para o slide ${index + 1}`);
        // Usa behavior: 'auto' para pular instantaneamente (sem animação suave)
        // Isso evita que o usuário veja a rolagem acontecendo ao dar F5
        targetSlide.scrollIntoView({ behavior: 'instant', block: 'start' });
        
        // Atualiza a bolinha ativa visualmente
        this._updateDotsUI(index);
      }
    }
  }

  _createNavDots() {
    let nav = document.getElementById('slide-nav');
    if (!nav) {
      nav = document.createElement('div');
      nav.id = 'slide-nav';
      document.body.appendChild(nav);
    }
    nav.innerHTML = '';
    this.navContainer = nav;

    this.slides.forEach((slide, index) => {
      const dot = document.createElement('div');
      dot.className = 'nav-dot';
      dot.dataset.index = index;
      dot.title = `Slide ${index + 1}`;
      
      dot.addEventListener('click', () => {
        // Ao clicar, salvamos manualmente também
        this._savePosition(index);
        slide.scrollIntoView({ behavior: 'smooth', block: 'start' });
      });

      nav.appendChild(dot);
    });
  }

  _initObserver() {
    const observerOptions = {
      root: null, // viewport
      threshold: 0.1 // Detecta quando 10% do slide está visível
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          // Encontra qual slide está ocupando a maior parte da tela?
          // Simplificação: se intersectar, consideramos candidato.
          // Melhor: verificar qual está mais próximo do centro.
          const index = this.slides.indexOf(entry.target);
          if (index !== -1) {
             // Só atualiza UI se estiver realmente "focado".
             // Aqui, vamos confiar que o scroll snap ou o usuário parou nele.
             // Para garantir, podemos checar se o top está proximo de 0?
             // Deixa simples por enquanto.
            this._updateDotsUI(index);
            this._savePosition(index);
          }
        }
      });
    }, observerOptions);

    this.slides.forEach(slide => observer.observe(slide));
  }

  // Separei a lógica visual para reutilizar no restorePosition
  _updateDotsUI(activeIndex) {
    if (!this.navContainer) return;
    const dots = this.navContainer.querySelectorAll('.nav-dot');
    dots.forEach(dot => dot.classList.remove('active'));
    
    if (dots[activeIndex]) {
      dots[activeIndex].classList.add('active');
    }
  }

  // --- NOVO MÉTODO: Salvar Posição ---
  _savePosition(index) {
    localStorage.setItem(this.storageKey, index);
  }

  _initKeyboard() {
    document.addEventListener('keydown', (e) => {
      // Ignora se estiver focado em iframe
      if (document.activeElement.tagName === 'IFRAME') return;

      const currentDot = this.navContainer.querySelector('.active');
      const currentIndex = currentDot ? parseInt(currentDot.dataset.index) : 0;
      const currentSlide = this.slides[currentIndex];

      // Definição de passo de scroll para navegação teclado e reveals
      // Como definimos altura baseada em 50vh por item:
      const scrollStep = window.innerHeight * 0.5;

      if (e.key === 'ArrowDown' || e.key === 'PageDown' || e.key === ' ' || e.key === 'Enter') {
        e.preventDefault();
        
        // Se tem reveals, vamos scrollar "dentro" do slide
        const revealItems = currentSlide.querySelectorAll('.reveal-block, .reveal-item');
        if (revealItems.length > 0) {
            // Verifica se chegamos no fim do slide
            const rect = currentSlide.getBoundingClientRect();
            // Se ainda tem espaço para rolar dentro do slide (rect.bottom > window.innerHeight)
            // Damos uma tolerância pequena de pixels
            if (rect.bottom > window.innerHeight + 10) {
                this.container.scrollBy({ top: scrollStep, behavior: 'smooth' });
                return;
            }
        }

        // Se não tem reveals ou já acabou, vai pro próximo
        const nextIndex = currentIndex + 1;
        if (nextIndex < this.slides.length) {
          this.slides[nextIndex].scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
      } 
      else if (e.key === 'ArrowUp' || e.key === 'PageUp') {
        e.preventDefault();
        
        // Funciona inverso: se estamos no meio de um slide com reveals
        const revealItems = currentSlide.querySelectorAll('.reveal-block, .reveal-item');
        if (revealItems.length > 0) {
             const rect = currentSlide.getBoundingClientRect();
             // Se o topo ainda está negativo (significa que scrollamos pra baixo)
             if (rect.top < -10) {
                 this.container.scrollBy({ top: -scrollStep, behavior: 'smooth' });
                 return;
             }
        }

        const nextIndex = currentIndex - 1;
        if (nextIndex >= 0) {
            // Ao voltar, queremos ir para o FIM do slide anterior se ele tiver reveals?
            // Por padrão behavior start vai pro topo.
            // Se quisermos ir pro fim, precisaríamos calcular.
            // Vamos simplificar indo pro topo por enquanto, comportamento padrão de slides.
          this.slides[nextIndex].scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
      }
    });

    // Ajuste no click para usar lógica parecida
    this.slides.forEach(slide => {
        slide.addEventListener('click', (e) => {
            if (e.target.tagName === 'A' || e.target.tagName === 'BUTTON') return;
            
            // Simula ArrowDown
            const scrollStep = window.innerHeight * 0.5;
            const revealItems = slide.querySelectorAll('.reveal-block, .reveal-item');
            
            if (revealItems.length > 0) {
                const rect = slide.getBoundingClientRect();
                if (rect.bottom > window.innerHeight + 10) {
                    this.container.scrollBy({ top: scrollStep, behavior: 'smooth' });
                    return;
                }
            }
            
            // Logica de ir pro proximo slide se nao tiver reveal ou acabou
            // Precisamos saber o index deste slide
            const idx = this.slides.indexOf(slide);
            const nextIndex = idx + 1;
             if (nextIndex < this.slides.length) {
                this.slides[nextIndex].scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
        });
    });
  }
}